// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"database/sql"
	"time"
)

type Users struct {
	ID                int64          `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	PhoneNumber       string         `db:"phone_number" json:"phone_number"`
	Otp               sql.NullString `db:"otp" json:"otp"`
	OtpExpirationTime sql.NullTime   `db:"otp_expiration_time" json:"otp_expiration_time"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}
